namespace NFramework.Core.CLI.SpectreConsoleUI.Generators.Templates.Application;

public static partial class ApplicationTemplate
{
    public const string Value = """
        // <auto-generated/>
        #nullable enable
        using global::Microsoft.Extensions.DependencyInjection;
        {{- if HasNamespace }}
        namespace {{ NamespaceName }};

        {{- end }}
        partial class {{ ApplicationTypeName }}
        {
            public static global::NFramework.Core.CLI.Abstractions.ICliApplication Create(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
            {
                global::System.ArgumentNullException.ThrowIfNull(services);
        {{- for command in Commands }}
                _ = global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton<{{ command.CommandTypeName }}>(services);
        {{- end }}

                global::Spectre.Console.Cli.CommandApp commandApp = new(new global::NFramework.Core.CLI.SpectreConsoleUI.IoC.TypeRegistrar(services));
                commandApp.Configure(configuration =>
                {
                    _ = global::Spectre.Console.Cli.ConfiguratorExtensions.SetApplicationName(configuration, {{ ApplicationNameLiteral }});
        {{- if ValidateExamples }}
                    _ = global::Spectre.Console.Cli.ConfiguratorExtensions.ValidateExamples(configuration);
        {{- end }}
        {{- for command in Commands }}
                    global::Spectre.Console.Cli.ICommandConfigurator {{ command.ConfiguratorName }} = configuration.AddCommand<{{ command.GeneratedAdapterTypeName }}>({{ command.CommandNameLiteral }});
                    _ = {{ command.ConfiguratorName }}.WithDescription({{ command.DescriptionLiteral }});
        {{- for example in command.Examples }}
                    _ = {{ command.ConfiguratorName }}.WithExample({{ example.ArgumentsLiteral }});
        {{- end }}

        {{- end }}
                });

                return new GeneratedCliApplication(commandApp);
            }
        }

        file sealed class GeneratedCliApplication(global::Spectre.Console.Cli.CommandApp commandApp) : global::NFramework.Core.CLI.Abstractions.ICliApplication
        {
            private readonly global::Spectre.Console.Cli.CommandApp _commandApp = commandApp;

            public int Run(string[] args)
            {
                global::System.ArgumentNullException.ThrowIfNull(args);
                return _commandApp.Run(args);
            }
        }
        {{- for command in Commands }}

        {{ command.GeneratedSettingsSource }}

        {{ command.GeneratedAdapterSource }}
        {{- end }}
        """;
}
